"""Add alembic to solarman schema

Revision ID: 1c48bbdad2a1
Revises: c1df11a0390b
Create Date: 2025-03-29 19:01:50.028238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c48bbdad2a1'
down_revision: Union[str, None] = 'c1df11a0390b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_site_history_device_sn_fkey', 'device_site_history', type_='foreignkey')
    op.drop_constraint('device_site_history_station_id_fkey', 'device_site_history', type_='foreignkey')
    op.create_foreign_key(None, 'device_site_history', 'devices', ['device_sn'], ['device_sn'], source_schema='solarman', referent_schema='solarman')
    op.create_foreign_key(None, 'device_site_history', 'stations', ['station_id'], ['id'], source_schema='solarman', referent_schema='solarman')
    op.drop_constraint('inverter_data_device_sn_fkey', 'inverter_data', type_='foreignkey')
    op.create_foreign_key(None, 'inverter_data', 'devices', ['device_sn'], ['device_sn'], source_schema='solarman', referent_schema='solarman')
    op.drop_index('idx_weather_ts', table_name='weather')
    op.create_index('idx_weather_ts', 'weather', ['ts'], unique=False, schema='solarman', postgresql_using='btree', postgresql_ops={'ts': 'desc'})
    op.drop_constraint('weather_station_id_fkey', 'weather', type_='foreignkey')
    op.drop_constraint('weather_device_sn_fkey', 'weather', type_='foreignkey')
    op.create_foreign_key(None, 'weather', 'stations', ['station_id'], ['id'], source_schema='solarman', referent_schema='solarman')
    op.create_foreign_key(None, 'weather', 'devices', ['device_sn'], ['device_sn'], source_schema='solarman', referent_schema='solarman')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather', schema='solarman', type_='foreignkey')
    op.drop_constraint(None, 'weather', schema='solarman', type_='foreignkey')
    op.create_foreign_key('weather_device_sn_fkey', 'weather', 'devices', ['device_sn'], ['device_sn'])
    op.create_foreign_key('weather_station_id_fkey', 'weather', 'stations', ['station_id'], ['id'])
    op.drop_index('idx_weather_ts', table_name='weather', schema='solarman', postgresql_using='btree', postgresql_ops={'ts': 'desc'})
    op.create_index('idx_weather_ts', 'weather', [sa.literal_column('ts DESC')], unique=False)
    op.drop_constraint(None, 'inverter_data', schema='solarman', type_='foreignkey')
    op.create_foreign_key('inverter_data_device_sn_fkey', 'inverter_data', 'devices', ['device_sn'], ['device_sn'])
    op.drop_constraint(None, 'device_site_history', schema='solarman', type_='foreignkey')
    op.drop_constraint(None, 'device_site_history', schema='solarman', type_='foreignkey')
    op.create_foreign_key('device_site_history_station_id_fkey', 'device_site_history', 'stations', ['station_id'], ['id'])
    op.create_foreign_key('device_site_history_device_sn_fkey', 'device_site_history', 'devices', ['device_sn'], ['device_sn'])
    # ### end Alembic commands ###
